export const NOTES_LIST_REQUEST = "NOTES_LIST_REQUEST";
export const NOTES_LIST_SUCCESS = "NOTES_LIST_SUCCESS";
export const NOTES_LIST_FAIL = "NOTES_LIST_FAIL";

export const NOTES_CREATE_REQUEST = "NOTES_CREATE_REQUEST";
export const NOTES_CREATE_SUCCESS = "NOTES_CREATE_SUCCESS";
export const NOTES_CREATE_FAIL = "NOTES_CREATE_FAIL";

export const NOTES_UPDATE_REQUEST = "NOTES_UPDATE_REQUEST";
export const NOTES_UPDATE_SUCCESS = "NOTES_UPDATE_SUCCESS";
export const NOTES_UPDATE_FAIL = "NOTES_UPDATE_FAIL";

export const NOTES_DELETE_REQUEST = "NOTES_DELETE_REQUEST";
export const NOTES_DELETE_SUCCESS = "NOTES_DELETE_SUCCESS";
export const NOTES_DELETE_FAIL = "NOTES_DELETE_FAIL";


export const BILLS_LIST_REQUEST = "BILLS_LIST_REQUEST";
export const BILLS_LIST_SUCCESS = "BILLS_LIST_SUCCESS";
export const BILLS_LIST_FAIL = "BILLS_LIST_FAIL";

export const BILLS_CREATE_REQUEST = "BILLS_CREATE_REQUEST";
export const BILLS_CREATE_SUCCESS = "BILLS_CREATE_SUCCESS";
export const BILLS_CREATE_FAIL = "BILLS_CREATE_FAIL";

export const BILLS_UPDATE_REQUEST = "BILLS_UPDATE_REQUEST";
export const BILLS_UPDATE_SUCCESS = "BILLS_UPDATE_SUCCESS";
export const BILLS_UPDATE_FAIL = "BILLS_UPDATE_FAIL";

export const BILLS_DELETE_REQUEST = "BILLS_DELETE_REQUEST";
export const BILLS_DELETE_SUCCESS = "BILLS_DELETE_SUCCESS";
export const BILLS_DELETE_FAIL = "BILLS_DELETE_FAIL";



