export enum ENUM_USER_STATUS_CODE_ERROR {
    USER_NOT_FOUND_ERROR = 5400,
    USER_IS_INACTIVE_ERROR = 5402,
    USER_ACTIVE_ERROR = 5405
}

export enum ENUM_USER_STATUS_CODE_SUCCESS {
    USER_LOGIN_SUCCESS = 1001,
}
